name: Multi-Environtonments CI Workflow

on: 
  push:
    branches: 
      - develop
      - staging
      - main 

permissions:
  id-token: write   # Required for OIDC authentication with AWS
  contents: read
  actions: read  

jobs:
  get-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "environment=develop" >> $GITHUB_OUTPUT
          else
            echo "Error: Branch not supported. Only develop, staging, and production branches are allowed." >> $GITHUB_STDERR
            exit 1
          fi

  build-and-push-ecr:
    needs: get-environment
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # environment: ${{ needs.get-environment.outputs.environment }}

    env: 
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID}}
      AWS_REGION: ${{ vars.AWS_REGION}}
      
      # Frontend
      REPOSITORY_NAME_FE: ${{ vars.REPOSITORY_NAME_FE }}
      DOCKER_FILE_PATH_FE: "fe/Dockerfile"
      DOCKER_BUILD_CONTEXT_FE: "fe"
      
      #Backend
      REPOSITORY_NAME_BE: ${{ vars.REPOSITORY_NAME_BE }}
      DOCKER_FILE_PATH_BE: "be/Dockerfile"
      DOCKER_BUILD_CONTEXT_BE: "be"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
        role-session-name: GitHubActions-ECR-${{ github.run_id }}
        aws-region: ${{ vars.AWS_REGION}}

    - name: Pre-build - Login ECR and set variables
      id: pre-build
      run: |
        echo "AWS CLI version:"
        aws --version
        
        # Login to ECR
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

        # Set repository URI
        REPOSITORY_URI_FE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME_FE
        REPOSITORY_URI_BE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME_BE
        
        # Generate tag with date + git hash
        DATE_TAG=$(date +%Y%m%d)
        GIT_HASH=$(git rev-parse --short HEAD)
        NEW_TAG="${DATE_TAG}-${GIT_HASH}"
        
        echo "Image Tag: $NEW_TAG"
        echo "FE Repository: $REPOSITORY_NAME_FE"
        echo "BE Repository: $REPOSITORY_NAME_BE"
        
        # Export variables for next steps
        echo "repository_uri_fe=$REPOSITORY_URI_FE" >> $GITHUB_OUTPUT
        echo "repository_uri_be=$REPOSITORY_URI_BE" >> $GITHUB_OUTPUT
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

    # Frontend Build and Push
    - name: Create .env file for FE build
      env:
        VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
      run: |
        echo "Creating .env file for Vite build..."
        cat > $DOCKER_BUILD_CONTEXT_FE/.env << EOF
        VITE_API_BASE_URL=$VITE_API_BASE_URL
        EOF
        echo ".env file created"
        cat $DOCKER_BUILD_CONTEXT_FE/.env

    - name: Build FE Docker image
      env:
        REPOSITORY_URI_FE: ${{ steps.pre-build.outputs.repository_uri_fe }}
        NEW_TAG: ${{ steps.pre-build.outputs.new_tag }}
      run: |
        echo "Build FE started on $(date)"
        echo "Building FE image with tag: $NEW_TAG"
        docker build \
          -t $REPOSITORY_URI_FE:$NEW_TAG \
          -f $DOCKER_FILE_PATH_FE \
          $DOCKER_BUILD_CONTEXT_FE

    - name: Push FE image to ECR
      env:
        NEW_TAG: ${{ steps.pre-build.outputs.new_tag }}
        REPOSITORY_URI_FE: ${{ steps.pre-build.outputs.repository_uri_fe }}
      run: |
        echo "Build FE completed on $(date)"
        echo "Pushing FE Docker image..."
        docker push $REPOSITORY_URI_FE:$NEW_TAG

    # Backend Build and Push
    - name: Build BE Docker image
      env:
        NEW_TAG: ${{ steps.pre-build.outputs.new_tag }}
        REPOSITORY_URI_BE: ${{ steps.pre-build.outputs.repository_uri_be }}
      run: |
        echo "Build BE started on $(date)"
        echo "Building BE image with tag: $NEW_TAG"
        
        docker build \
          -t $REPOSITORY_URI_BE:$NEW_TAG \
          -f $DOCKER_FILE_PATH_BE \
          $DOCKER_BUILD_CONTEXT_BE

    - name: Push BE image to ECR
      env:
        NEW_TAG: ${{ steps.pre-build.outputs.new_tag }}
        REPOSITORY_URI_BE: ${{ steps.pre-build.outputs.repository_uri_be }}
      run: |
        echo "Build BE completed on $(date)"
        echo "Pushing BE Docker image..."
        docker push $REPOSITORY_URI_BE:$NEW_TAG
