name: Multi-Environtonments CI Workflow

on: 
  push:
    branches: 
      - develop
      - staging
      - main 

permissions:
  id-token: write   # Required for OIDC authentication with AWS
  contents: read
  actions: read  

jobs:
  get-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - id: set-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "environment=develop" >> $GITHUB_OUTPUT
          else
            echo "Error: Branch not supported. Only develop, staging, and production branches are allowed." >> $GITHUB_STDERR
            exit 1
          fi

  
  build-and-push-ecr:
    needs: get-environment
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # environment: ${{ needs.get-environment.outputs.environment }}

    env: 
      AWS_ACCOUNT_ID: "481665128807"
      AWS_REGION: "us-east-1"
      REPOSITORY_NAME: "test-github-action"
      DOCKER_FILE_PATH: "Dockerfile"
      DOCKER_BUILD_CONTEXT: "."

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::481665128807:role/github-oidc-role"
        role-session-name: GitHubActions-FE-${{ github.run_id }}
        aws-region: "us-east-1"

    - name: Pre-build - Login ECR and set variables
      id: pre-build
      run: |
        echo "AWS CLI version:"
        aws --version
        
        # Login to ECR
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        
        # Set repository URI
        REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME
        
        # Generate new tag with date + git hash
        DATE_TAG=$(date +%Y%m%d)
        GIT_HASH=$(git rev-parse --short HEAD)
        NEW_TAG="${DATE_TAG}-${GIT_HASH}"
        echo "New Tag: $NEW_TAG"
        
        # Export variables for next steps
        echo "repository_uri=$REPOSITORY_URI" >> $GITHUB_OUTPUT
        echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

    - name: Create .env file for build
      env:
        VITE_API_BASE_URL: "<VITE_API_BASE_URL>"
      run: |
        echo "Creating .env file for Vite build..."
        cat > .env << EOF
        VITE_API_BASE_URL=$VITE_API_BASE_URL
        EOF

    - name: Build Docker image
      env:
        REPOSITORY_URI: ${{ steps.pre-build.outputs.repository_uri }}
        NEW_TAG: ${{ steps.pre-build.outputs.new_tag }}
      run: |
        echo "Build started on $(date)"
        echo "Building image with tag: $NEW_TAG"
        docker build \
          -t $REPOSITORY_URI:$NEW_TAG \
          -f $DOCKER_FILE_PATH \
          $DOCKER_BUILD_CONTEXT

    - name: Post-build - Push image to ECR
      env:
        REPOSITORY_URI: ${{ steps.pre-build.outputs.repository_uri }}
        NEW_TAG: ${{ steps.pre-build.outputs.new_tag }}
      run: |
        echo "Build completed on $(date)"
        echo "Pushing Docker image..."
        
        docker push $REPOSITORY_URI:$NEW_TAG